#!/usr/bin/env python

import os
import roslaunch
import rospkg
import rospy
import sys

from human_cues_tag_simulator import simulator, tools

ENV_DEFAULT = 's11'


def main(env=ENV_DEFAULT):
    """Main function for running the node"""
    # Generate a world file, containing the map, tags, and robot
    simulator.generateWorldFile(env)

    # Launch stage with the generated world file
    uuid = roslaunch.rlutil.get_or_generate_uuid(None, True)
    roslaunch.configure_logging(uuid)
    node = roslaunch.core.Node(
        'stage_ros', 'stageros', 'stage', args='-u ' + tools.worldPath(env))
    launch = roslaunch.scriptapi.ROSLaunch()
    launch.start()
    process = launch.launch(node)

    # Run until the process dies
    while process.is_alive():
        rospy.sleep(0.5)


if __name__ == '__main__':
    if len(sys.argv) == 2:
        main(sys.argv[1])
    else:
        main()
