local_costmap:
  global_frame: odom
  width: 6.0
  height: 6.0
  resolution: 0.05
  rolling_window: true
  update_frequency: 5.0
  publish_frequency: 1.0
  plugins:
    - { name: static_layer, type: "costmap_2d::StaticLayer" }
    - { name: obstacle_layer, type: "costmap_2d::ObstacleLayer" }
    - { name: inflation_layer, type: "costmap_2d::InflationLayer" }
