# Global parameters
robot_radius: 0.25

# Plugin layer parameterisations
obstacle_layer:
  observation_sources: scan_laser scan_depth
  footprint_clearing_enabled: true

  scan_laser: {
    sensor_frame: laser,
    data_type: LaserScan,
    topic: /scan_laser_fixed,
    marking: true,
    clearing: true,
    raytrace_range: 8.1,
    obstacle_range: 8.1
  }

  scan_depth: {
    sensor_frame: camera_front,
    data_type: LaserScan,
    topic: /scan_depth,
    marking: true,
    clearing: true,
    raytrace_range: 10.0,
    obstacle_range: 2.0
  }

static_layer:
  trinary_costmap: false

inflation_layer:
  inflation_radius: 1.75
  cost_scaling_factor: 2.58
