TrajectoryPlannerROS:
  # Robot configuration parameters
  min_vel_x: 0.05
  max_vel_x: 0.4
  min_vel_theta: -0.4
  max_vel_theta: 0.4 
  min_in_place_vel_theta: 0.3
  escape_vel: -0.01

  acc_lim_theta: 0.25 #2.5 
  acc_lim_x: 0.1 
  acc_lim_y: 0 # Non-holynomic robot

  holonomic_robot: false

  # Goal tolerance parameters
  yaw_goal_tolerance: 0.26 # ~15 degrees
  xy_goal_tolerance: 0.3

  # Forward simulation parameters
  sim_time: 4.0 
  #angular_sim_granularity: 0.01745 # ~1 degrees
  vtheta_samples: 40
  vx_samples: 20

  # Trajectory scoring parameters
  dwa: false

  pdist_scale: 2.6 
  gdist_scale: 1.0
  occdist_scale: 0.02 

  heading_scoring: false
  heading_scoring_timestep: 0.8
